C_OBJS=persist.o
ASM_OBJS=
COMPONENT=per.o
INTERFACES=torrent
DEPENDENCIES=printc cbufp cbuf_c evt name_server sched lock mem_mgr_large valloc uniq_map torrent ll_log

include ../../Makefile.subsubdir

