C_OBJS=pop_server_file.o
ASM_OBJS=
COMPONENT=popcgi.o
INTERFACES=
DEPENDENCIES=printc rtorrent sched cbufp cbuf_c evt name_server mem_mgr_large valloc lock timed_blk ll_log
FN_PREPEND=server_
IF_LIB=

include ../../Makefile.subsubdir
