/* IDL generated code ver 0.1 ---  Mon Nov 23 18:29:29 2015 */


/* How IDL know when to use simple stack or stack? */
#include <cos_asm_server_stub_simple_stack.h>
//#include <cos_asm_server_stub.h>
    
.text
    
cos_asm_server_stub_spdid(mman_get_page)
cos_asm_server_stub_spdid(__mman_alias_page)
cos_asm_server_stub_spdid(mman_revoke_page)
cos_asm_server_stub_spdid(mman_release_page)
cos_asm_server_stub_spdid(mman_get_page_exist)
cos_asm_server_stub_spdid(mman_reflect)
