C_OBJS=udp_loop.o
ASM_OBJS=
COMPONENT=udp.o
INTERFACES=
DEPENDENCIES=cbufp cbuf_c torrent printc lock sched valloc evt name_server mem_mgr_large ll_log uniq_map
FN_PREPEND=from_ server_

include ../../Makefile.subsubdir

