C_OBJS=udp_loop.o
ASM_OBJS=
COMPONENT=udp.o
INTERFACES=
DEPENDENCIES=cbufp cbuf_c torrent printc lock sched valloc evt name_server mem_mgr_large ll_log
FN_PREPEND=from_

include ../../Makefile.subsubdir

