C_OBJS=conn_mgr.o
ASM_OBJS=
COMPONENT=stconnmt.o
INTERFACES=lateness_report
DEPENDENCIES=torrent printc mem_mgr_large sched valloc cbufp cbuf_c evt name_server periodic_wake net_transport lock ll_log
FN_PREPEND=server_
IF_LIB=

include ../../Makefile.subsubdir
