C_OBJS=trans.o
COMPONENT=utrans.o
DEPENDENCIES=cbufp cbuf_c printt valloc mem_mgr_large unit_cbuf sched lock torrent evt name_server ll_log uniq_map
FN_PREPEND=print_ server_

include ../../Makefile.subsubdir
