/* IDL generated code ver 0.1 ---  Mon Nov 23 20:12:46 2015 */


/* How IDL know when to use simple stack or stack? */
#include <cos_asm_server_stub_simple_stack.h>
//#include <cos_asm_server_stub.h>
    
.text
    
cos_asm_server_fn_stub_spdid(evt_wait,__ser_evt_wait)
cos_asm_server_fn_stub_spdid(evt_client_fault_notification,__ser_evt_client_fault_notification)
cos_asm_server_stub_spdid(evt_split)
cos_asm_server_stub_spdid(evt_trigger)
cos_asm_server_stub_spdid(evt_free)
cos_asm_server_stub_spdid(evt_grp_wait)
cos_asm_server_stub_spdid(evt_set_prio)
cos_asm_server_stub_spdid(evt_create) 
cos_asm_server_stub_spdid(evt_stats) 
cos_asm_server_stub_spdid(evt_stats_len)
cos_asm_server_stub_spdid(evt_split_exist)

cos_asm_server_stub_spdid(evt_upcall_creator)