/* IDL generated code ver 0.1 ---  Mon Nov 23 20:13:14 2015 */


/* How IDL know when to use simple stack or stack? */
#include <cos_asm_server_stub_simple_stack.h>
//#include <cos_asm_server_stub.h>
    
.text
    
cos_asm_server_stub_spdid(periodic_wake_create)
cos_asm_server_stub_spdid(periodic_wake_wait)
cos_asm_server_stub_spdid(periodic_wake_remove)
cos_asm_server_stub_spdid(periodic_wake_create_exist)
cos_asm_server_stub(periodic_wake_get_misses)
cos_asm_server_stub(periodic_wake_get_deadlines)
cos_asm_server_stub(periodic_wake_get_lateness)
cos_asm_server_stub(periodic_wake_get_miss_lateness)
cos_asm_server_stub(periodic_wake_get_period)
