C_OBJS=tar_test.o
ASM_OBJS=
COMPONENT=tart.o
INTERFACES=
DEPENDENCIES=printc torrent sched cbufp cbuf_c evt name_server mem_mgr_large valloc lock ll_log uniq_map
IF_LIB=
FN_PREPEND=server_

include ../../Makefile.subsubdir

