C_OBJS=mbox_server.o
ASM_OBJS=
COMPONENT=micro_mbox_server.o
INTERFACES=
DEPENDENCIES=periodic_wake printc mbtorrent sched cbufp cbuf_c evt name_server mem_mgr_large valloc lock uniq_map
IF_LIB=

include ../../Makefile.subsubdir
