C_OBJS=f.o
ASM_OBJS=
COMPONENT=fpu.o
INTERFACES=
#DEPENDENCIES=sched printc mem_mgr timed_blk ll_log
DEPENDENCIES=sched printc mem_mgr valloc timed_blk ll_log
IF_LIB=

include ../../Makefile.subsubdir
