/* IDL generated code ver 0.1 ---  Mon Nov 23 20:12:23 2015 */


/* How IDL know when to use simple stack or stack? */
#include <cos_asm_server_stub_simple_stack.h>
//#include <cos_asm_server_stub.h>
    
.text
    
cos_asm_server_fn_stub_spdid(lock_component_take,__ser_lock_component_take)
cos_asm_server_fn_stub_spdid(lock_client_fault_notification,__ser_lock_client_fault_notification)
cos_asm_server_stub_spdid(lock_component_alloc)
cos_asm_server_stub_spdid(lock_component_pretake)
cos_asm_server_stub_spdid(lock_component_release)
cos_asm_server_stub_spdid(lock_component_free)
cos_asm_server_stub_spdid(lock_stats)
cos_asm_server_stub_spdid(lock_stats_len)
