C_OBJS=mbox_client.o
ASM_OBJS=
COMPONENT=micro_mbox_client.o
INTERFACES=
DEPENDENCIES=periodic_wake printc torrent sched cbufp cbuf_c evt name_server mem_mgr_large valloc lock uniq_map
IF_LIB=
FN_PREPEND=server_

include ../../Makefile.subsubdir
