C_OBJS=ramfs_ft_test2.o
ASM_OBJS=
COMPONENT=ramfs_rec_test2.o
INTERFACES=ramfs_test2
DEPENDENCIES=printc torrent sched cbufp cbuf_c evt name_server mem_mgr_large valloc lock uniq_map ll_log
FN_PREPEND=server_
IF_LIB=

include ../../Makefile.subsubdir
