/* IDL generated code ver 0.1 ---  Tue Nov 24 09:16:26 2015 */


/* How IDL know when to use simple stack or stack? */
//#include <cos_asm_server_stub_simple_stack.h>
#include <cos_asm_server_stub.h>
    
.text
    
cos_asm_server_fn_stub_spdid(tsplit,__ser_tsplit)
cos_asm_server_fn_stub_spdid(treadp,__ser_treadp)
cos_asm_server_stub_spdid(twritep)
cos_asm_server_stub_spdid(trelease)
cos_asm_server_stub_spdid(tmerge)
cos_asm_server_stub_spdid(tread)
cos_asm_server_stub_spdid(twrite)
cos_asm_server_stub_spdid(trmeta)
cos_asm_server_stub_spdid(twmeta)
