/* IDL generated code ver 0.1 ---  Fri Nov 27 10:24:09 2015 */

/**
 * Copyright 2011 by Gabriel Parmer, gparmer@gwu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub.h>
.text	
cos_asm_server_stub_spdid(tmerge)
cos_asm_server_stub_spdid(trelease)
cos_asm_server_stub_spdid(tread)
cos_asm_server_stub_spdid(twrite)
cos_asm_server_stub_spdid(twritep)
cos_asm_server_stub_spdid(trmeta)
cos_asm_server_stub_spdid(twmeta)

cos_asm_server_fn_stub_spdid(tsplit,__ser_tsplit)
cos_asm_server_fn_stub_spdid(treadp,__ser_treadp)